services:
- type: web
  name: next-js
  env: node
  plan: starter
  buildCommand: yarn --production=false; yarn build
  startCommand: yarn start
  # envVars:
  # - key: GQL_SERVER
  #   fromService:
  #     name: hasura
  #     type: web
  #     envVarKey: HASURA_GRAPHQL_ENDPOINT
  - key: NODE_ENV
    value: production
- type: web
  name: hasura
  env: docker
  dockerfilePath: "./hasura-service/Dockerfile"
  autoDeploy: false
  healthCheckPath: /healthz
  envVars:
  - key: HASURA_GRAPHQL_DATABASE_URL
    fromDatabase:
      name: hasura
      property: connectionString
  - key: HASURA_GRAPHQL_ENABLE_CONSOLE
    value: true
  - key: PORT
    value: 10000
databases:
- name: hasura